### ISSUE TITLE
Fix Slack-to-text emojis

### ISSUE THREAD

**Issue by tomerovadia** [tomerovadia/VoterHelpLine#78]

**Comment by tomerovadia** [comment]
@fongandrew Right now emojis sent by text render correctly in Slack, but not vice versa. Do you know how to address this? I imagine volunteers will end up using emojis at least occasionally, and right now it appears as text on a phone.

**Comment by fongandrew** [comment]
Slack sends its emojis in a colon text format like `:emoji:` because it allows for custom emoji not supported elsewhere 😐 

Assuming the user is sending a standard unicode emoji though, we basically have to convert something like `:smiley:` to `'\uD83D\uDE00'`. We can probably just use this thing to do it: https://github.com/iamcal/js-emoji
